version: '2.1'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.app
#    image: app
#    ports:
#      - "5000:5000"
#    env_file: .env
##    depends_on:
##      - cassandra
##    links:
##      - cassandra
#    volumes:
#      - type: bind
#        source: ./
#        target: /opt/

  cassandra:
      image: cassandra:3.11.2
      container_name: cassandra
      env_file:
        - cassandra/cassandra.env
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./data/cassandra:/var/lib/cassandra
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

  cqlsh:
    image: cassandra:3.11
    entrypoint: cqlsh cassandra
    volumes:
      - ./cassandra/schema.cql:/schema.cql

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:3.11.2
#      depends_on:
#        cassandra:
#          condition: service_healthy
      volumes:
        - ./cassandra/schema.cql:/schema.cql
      command: /bin/bash -c "echo loading cassandra keyspace && cqlsh 192.168.99.100 -f /schema.cql"
